codecov: 
 token: 976f6e2a-d145-49ef-9a42-53385cf2a234
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

